### ISSUE TITLE
Examples must adhere to PSR-12 standard

### ISSUE THREAD

**Issue by 20jam** [20jam/php-oop#3]
As pointed out by @colshrapnel the example code should adhere to coding standard such as PSR-2 and PSR-12.

**Comment by 20jam** [comment]
#5

**Comment by dahse89** [comment]
You should integrate https://github.com/squizlabs/PHP_CodeSniffer to achieve PSR 12 formating. Maybe i will submit a pull request in the next days.

**Comment by yarimadam** [comment]
I think we should target a PHP version and enforce code style based on the version.

**Comment by 20jam** [comment]
How about Php 7, I started adopting some code styles from PSR-2 , PSR-12 in my code editor such 4 space indentation, I’m still reading the style guides and soon will update the examples.

**Comment by yarimadam** [comment]
Sure, it should be all 7, but what about specific version? I suggest the most recent version 7.4 to cover typed properties.

apart from the version, i think it's a good idea to create a milestone and start assigning the issues. by that way we can tell which feature will go live in which version etc.

**Comment by 20jam** [comment]
Yah, the most recent.

hmm milestones, give me an example workflow and how to do it.

**Comment by dahse89** [comment]
I start my  PR, now. I will also do add the php version to the composer.json

**Comment by dahse89** [comment]
There it is https://github.com/20jam/php-oop/pull/8/files

**Comment by 20jam** [comment]
Thanks to #8 and @dahse89 we have resolved this issue.
